name: dart2wasm
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none
environment:
  sdk: ^3.3.0

# Use 'any' constraints here; we get our versions from the DEPS file.
dependencies:
  _fe_analyzer_shared: any
  _js_interop_checks: any
  args: any
  build_integration: any
  collection: any
  front_end: any
  kernel: any
  vm: any
  wasm_builder: any
  path: any

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  lints: any



dependency_overrides:
  _fe_analyzer_shared: 
    path: ../_fe_analyzer_shared
  _js_interop_checks: 
    path: ../_js_interop_checks
  args: any
  build_integration: 
    path: ../build_integration
  collection: any
  front_end: 
    path: ../front_end
  kernel: 
    path: ../kernel
  vm: 
    path: ../vm
  wasm_builder: 
    path: ../wasm_builder