name: dart2bytecode
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

# Use 'any' constraints here; we get our versions from the DEPS file.
dependencies:
  args: any
  front_end: any
  kernel: any
  vm: any

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  expect: any
  test: any




dependency_overrides:
  _fe_analyzer_shared: 
    path: ../_fe_analyzer_shared
  _js_interop_checks: 
    path: ../_js_interop_checks
  args: any
  build_integration: 
    path: ../build_integration
  collection: any
  front_end: 
    path: ../front_end
  kernel: 
    path: ../kernel
  vm: 
    path: ../vm
  wasm_builder: 
    path: ../wasm_builder