name: dart2cpp
description: Dart to C++ compiler and runtime library
version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.16.0

dependency_overrides:
  kernel:
    path: ../kernel
  front_end:
    path: ../front_end
  _fe_analyzer_shared:
    path: ../_fe_analyzer_shared
