/// 简化的转换逻辑测试
/// 测试dart2cpp的核心转换功能
import 'dart:io';
import 'lib/dart2cpp.dart';

void main() async {
  print('🧪 开始简化转换逻辑测试');
  print('=' * 50);

  int passedTests = 0;
  int totalTests = 0;

  // 测试1: 编译器版本和特性
  totalTests++;
  print('\n📝 测试1: 编译器版本和特性');
  try {
    final version = Dart2CppCompiler.version;
    final features = Dart2CppCompiler.supportedFeatures;

    if (version == '2.0.0' && features.length >= 10) {
      print('✅ 编译器信息正确');
      print('  • 版本: $version');
      print('  • 特性数量: ${features.length}');
      passedTests++;
    } else {
      print('❌ 编译器信息不正确');
    }
  } catch (e) {
    print('❌ 编译器信息测试异常: $e');
  }

  // 测试2: 运行时支持添加
  totalTests++;
  print('\n📝 测试2: 运行时支持添加');
  try {
    final originalCode = '''
int main() {
  return 0;
}
''';

    final codeWithRuntime = Dart2CppCompiler.addRuntimeSupport(originalCode);

    final checks = {
      '包含头文件': codeWithRuntime.contains('#include'),
      '包含工具宏': codeWithRuntime.contains('#define dart_'),
      '包含原始代码': codeWithRuntime.contains('int main()'),
      '包含版本信息': codeWithRuntime.contains('Generated by dart2cpp'),
    };

    final passedChecks = checks.values.where((v) => v).length;
    if (passedChecks >= 3) {
      print('✅ 运行时支持添加正确 ($passedChecks/4)');
      checks.forEach((key, value) {
        print('  • $key: ${value ? "✅" : "❌"}');
      });
      passedTests++;
    } else {
      print('❌ 运行时支持添加不完整 ($passedChecks/4)');
    }
  } catch (e) {
    print('❌ 运行时支持添加测试异常: $e');
  }

  // 测试3: 代码优化
  totalTests++;
  print('\n📝 测试3: 代码优化');
  try {
    final result1 = await UnifiedCompiler.compileSource(
      '''
void main() {
  print('Test');
}
''',
      config: CompilerConfig(
        includeRuntime: true,
        optimize: false,
        verbose: false,
      ),
    );

    final result2 = await UnifiedCompiler.compileSource(
      '''
void main() {
  print('Test');
}
''',
      config: CompilerConfig(
        includeRuntime: true,
        optimize: true,
        verbose: false,
      ),
    );

    if (result1.isSuccess && result2.isSuccess) {
      print('✅ 代码优化正确');
      print('  • 未优化代码大小: ${result1.codeSize} 字符');
      print('  • 优化后代码大小: ${result2.codeSize} 字符');
      print('  • 优化效果: ${result1.codeSize - result2.codeSize} 字符');
      passedTests++;
    } else {
      print('❌ 代码优化异常');
    }
  } catch (e) {
    print('❌ 代码优化测试异常: $e');
  }

  // 测试4: 简单编译流程
  totalTests++;
  print('\n📝 测试4: 简单编译流程');
  try {
    final result = await UnifiedCompiler.compileSource(
      '''
void main() {
  print('Hello, World!');
}
''',
      config: CompilerConfig(
        includeRuntime: true,
        optimize: false,
        verbose: false,
      ),
    );

    if (result.isSuccess) {
      final cppCode = result.cppCode;
      final checks = {
        '包含头文件': cppCode.contains('#include'),
        '包含主函数': cppCode.contains('int main()'),
        '包含工具宏': cppCode.contains('#define dart_'),
        '包含版本信息': cppCode.contains('Generated by dart2cpp'),
      };

      final passedChecks = checks.values.where((v) => v).length;
      if (passedChecks >= 3) {
        print('✅ 简单编译流程正确 ($passedChecks/4)');
        checks.forEach((key, value) {
          print('  • $key: ${value ? "✅" : "❌"}');
        });
        passedTests++;
      } else {
        print('❌ 简单编译流程不完整 ($passedChecks/4)');
      }
    } else {
      print('❌ 简单编译流程失败');
      for (final error in result.errors) {
        print('  • $error');
      }
    }
  } catch (e) {
    print('❌ 简单编译流程测试异常: $e');
  }

  // 测试5: 文件编译流程
  totalTests++;
  print('\n📝 测试5: 文件编译流程');
  try {
    // 创建测试文件
    final testFile = File('simple_test.dart');
    await testFile.writeAsString('''
void main() {
  var x = 42;
  print('x = \$x');
}
''');

    final result = await UnifiedCompiler.compileFile(
      'simple_test.dart',
      config: CompilerConfig(
        outputPath: 'simple_test.cpp',
        includeRuntime: true,
        optimize: false,
        verbose: false,
      ),
    );

    if (result.isSuccess && File('simple_test.cpp').existsSync()) {
      print('✅ 文件编译流程正确');
      print('  • 输出文件存在: ${File('simple_test.cpp').existsSync()}');
      print('  • 代码大小: ${result.codeSize} 字符');
      print('  • 编译时间: ${result.compilationTime.inMilliseconds}ms');
      passedTests++;

      // 清理测试文件
      await testFile.delete();
      await File('simple_test.cpp').delete();
    } else {
      print('❌ 文件编译流程失败');
    }
  } catch (e) {
    print('❌ 文件编译流程测试异常: $e');
  }

  // 测试6: 错误处理
  totalTests++;
  print('\n📝 测试6: 错误处理');
  try {
    final result = await UnifiedCompiler.compileSource(
      '''
void main() {
  // 故意包含语法错误
  var x = ;
  print('This should fail');
}
''',
      config: CompilerConfig(
        includeRuntime: true,
        optimize: false,
        verbose: false,
      ),
    );

    if (!result.isSuccess && result.errors.isNotEmpty) {
      print('✅ 错误处理正确');
      print('  • 检测到错误: ${result.errors.length} 个');
      for (final error in result.errors) {
        print('  • $error');
      }
      passedTests++;
    } else {
      print('❌ 错误处理异常: 应该检测到错误但没有');
    }
  } catch (e) {
    print('✅ 错误处理正确: 捕获到异常 $e');
    passedTests++;
  }

  // 测试7: 性能测试
  totalTests++;
  print('\n📝 测试7: 性能测试');
  try {
    final stopwatch = Stopwatch()..start();

    final result = await UnifiedCompiler.compileSource(
      '''
void main() {
  print('Performance test');
}
''',
      config: CompilerConfig(
        includeRuntime: true,
        optimize: true,
        verbose: false,
      ),
    );

    stopwatch.stop();

    if (result.isSuccess) {
      final compilationTime = result.compilationTime.inMilliseconds;
      final totalTime = stopwatch.elapsedMilliseconds;

      print('✅ 性能测试通过');
      print('  • 编译时间: ${compilationTime}ms');
      print('  • 总时间: ${totalTime}ms');
      print('  • 代码大小: ${result.codeSize} 字符');

      if (compilationTime < 100) {
        print('  • 性能评级: 优秀 (< 100ms)');
        passedTests++;
      } else if (compilationTime < 500) {
        print('  • 性能评级: 良好 (< 500ms)');
        passedTests++;
      } else {
        print('  • 性能评级: 需要优化 (> 500ms)');
      }
    } else {
      print('❌ 性能测试失败');
    }
  } catch (e) {
    print('❌ 性能测试异常: $e');
  }

  // 测试总结
  print('\n' + '=' * 50);
  print('📊 简化转换逻辑测试总结');
  print('总测试数: $totalTests');
  print('通过测试: $passedTests');
  print('失败测试: ${totalTests - passedTests}');
  print('通过率: ${(passedTests / totalTests * 100).toStringAsFixed(1)}%');

  if (passedTests == totalTests) {
    print('🎉 所有简化测试通过！');
  } else {
    print('⚠️ 部分简化测试失败，需要修复');
  }

  // 总体评估
  print('\n📈 总体评估');
  if (passedTests >= totalTests * 0.8) {
    print('🟢 转换逻辑整体良好 (通过率 >= 80%)');
    print('   建议: 可以继续完善功能');
  } else if (passedTests >= totalTests * 0.6) {
    print('🟡 转换逻辑基本可用 (通过率 >= 60%)');
    print('   建议: 需要修复部分问题');
  } else {
    print('🔴 转换逻辑需要重大改进 (通过率 < 60%)');
    print('   建议: 需要重新审视实现');
  }

  // 问题分析
  print('\n🔍 问题分析');
  print('当前实现的主要问题:');
  print('1. 缺少真正的Dart源码解析');
  print('2. 生成的C++代码只有框架，没有实际转换');
  print('3. 需要实现真正的Kernel AST解析');
  print('4. 转换器组件存在但无法被正确调用');

  print('\n💡 改进建议');
  print('1. 优先实现真正的Dart源码解析');
  print('2. 修复Kernel AST的API调用');
  print('3. 完善转换器的集成测试');
  print('4. 添加更多的实际转换测试');
}
