// Generated by dart2cpp v2.0.0
#include "../cpp/core/dart2cpp.h"
#include "../cpp/core/object.h"
#include "../cpp/core/dart_async.h"
#include "../cpp/core/dart_oop_extensions.h"
#include <iostream>
#include <memory>

// 工具宏定义
#define dart_print(value) \
    do { \
        std::cout << (value).toString().getValue() << std::endl; \
    } while(0)

#define dart_int(value) Int(value)
#define dart_double(value) Double(value)
#define dart_bool(value) Bool(value)
#define dart_string(value) String(value)

#include "../pkg/dart2bytecode/base/object.h"
#include "../pkg/dart2bytecode/base/dart_oop_extensions.h"
#include "../pkg/dart2bytecode/base/dart_async.h"
#include <iostream>

// 工具宏定义
#define dart_print(value) \
    do { \
        std::cout << (value).toString().getValue() << std::endl; \
    } while(0)

#define dart_int(value) Int(value)
#define dart_double(value) Double(value)
#define dart_bool(value) Bool(value)
#define dart_string(value) String(value)

// ============================================================================
// 主函数
// ============================================================================

int main() {
  try {
    return 0;
  } catch (const std::exception& e) {
    std::cerr << "Error: " << e.what() << std::endl;
    return 1;
  }
}
