// Generated by dart2cpp from hello.dart

#include "dart2cpp.h"
#include <iostream>

int main() {
    // Simple types
    String message = String("Hello from Dart2CPP!");
    Int count = Int(5);
    
    std::cout << message.getValue() << std::endl;
    std::cout << "Count: " << count.toString().getValue() << std::endl;
    
    // List example
    ObjectPtr<List<Int>> numbers = List<Int>::create();
    for (Int i = Int(1); i.toInt() <= count.toInt(); ++i) {
        numbers->add(i);
    }
    
    std::cout << "Numbers: ";
    for (Int i = Int(0); i.toInt() < numbers->size().toInt(); ++i) {
        std::cout << numbers->get(i).toString().getValue() << " ";
    }
    std::cout << std::endl;
    
    return 0;
}

