#!/bin/bash

# Dart to C++ 批量转换脚本
# 将 sample/dart 目录下的所有 .dart 文件转换为 C++ 文件并放到 sample/cpp 目录

set -e  # 遇到错误立即退出

# 脚本配置
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DART_DIR="$SCRIPT_DIR/dart"
CPP_DIR="$SCRIPT_DIR/cpp"
DART2CPP_BIN="$PROJECT_ROOT/bin/dart2cpp.dart"

# 颜色输出
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 打印带颜色的消息
print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# 检查必要的工具和文件
check_prerequisites() {
    print_info "检查前置条件..."
    
    # 检查 dart 命令
    if ! command -v dart &> /dev/null; then
        print_error "Dart SDK 未找到，请确保 dart 命令在 PATH 中"
        exit 1
    fi
    
    # 检查 dart2cpp 工具
    if [ ! -f "$DART2CPP_BIN" ]; then
        print_error "dart2cpp 工具未找到: $DART2CPP_BIN"
        exit 1
    fi
    
    # 检查输入目录
    if [ ! -d "$DART_DIR" ]; then
        print_error "输入目录不存在: $DART_DIR"
        exit 1
    fi
    
    print_success "前置条件检查通过"
}

# 清理输出目录
clean_output_dir() {
    print_info "清理输出目录: $CPP_DIR"
    
    if [ -d "$CPP_DIR" ]; then
        rm -rf "$CPP_DIR"
        print_success "已清理输出目录"
    fi
    
    mkdir -p "$CPP_DIR"
    print_success "已创建输出目录: $CPP_DIR"
}

# 转换单个文件
convert_file() {
    local dart_file="$1"
    local relative_path="$2"
    local cpp_file="$CPP_DIR/${relative_path%.dart}.cpp"
    
    print_info "转换: $relative_path"
    
    # 创建输出目录（如果需要）
    local cpp_dir="$(dirname "$cpp_file")"
    mkdir -p "$cpp_dir"
    
    # 执行转换
    if dart "$DART2CPP_BIN" --output "$cpp_file" --optimize --verbose "$dart_file"; then
        print_success "✅ $relative_path -> ${relative_path%.dart}.cpp"
        return 0
    else
        print_error "❌ 转换失败: $relative_path"
        return 1
    fi
}

# 批量转换所有 Dart 文件
convert_all_files() {
    print_info "开始批量转换 Dart 文件..."
    
    local total_files=0
    local success_files=0
    local failed_files=0
    
    # 使用临时文件存储find结果，避免管道子shell问题
    local temp_file=$(mktemp)
    find "$DART_DIR" -name "*.dart" -type f > "$temp_file"
    
    # 读取文件列表并转换
    while read -r dart_file; do
        if [ -n "$dart_file" ]; then
            # 计算相对路径
            local relative_path="${dart_file#$DART_DIR/}"
            
            total_files=$((total_files + 1))
            
            if convert_file "$dart_file" "$relative_path"; then
                success_files=$((success_files + 1))
            else
                failed_files=$((failed_files + 1))
            fi
            
            echo  # 添加空行分隔
        fi
    done < "$temp_file"
    
    # 清理临时文件
    rm -f "$temp_file"
    
    # 打印转换统计
    echo "=================================="
    print_info "转换统计:"
    echo "  总文件数: $total_files"
    print_success "  成功: $success_files"
    if [ $failed_files -gt 0 ]; then
        print_error "  失败: $failed_files"
    else
        echo "  失败: $failed_files"
    fi
    echo "=================================="
    
    if [ $failed_files -eq 0 ] && [ $total_files -gt 0 ]; then
        print_success "🎉 所有文件转换成功！"
        return 0
    elif [ $total_files -eq 0 ]; then
        print_warning "⚠️  没有找到 .dart 文件"
        return 1
    else
        print_warning "⚠️  部分文件转换失败"
        return 1
    fi
}

# 创建 Makefile
create_makefile() {
    print_info "创建 Makefile..."
    
    local makefile="$CPP_DIR/Makefile"
    
    cat > "$makefile" << 'EOF'
# Makefile for Sample C++ Files
# Generated by convert_all.sh

CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -I../../cpp/core -Wno-unused-parameter -Wno-deprecated-copy-with-user-provided-copy
LDFLAGS = 

# 查找所有 .cpp 文件
SOURCES = $(wildcard *.cpp)
TARGETS = $(SOURCES:.cpp=.out)

# 默认目标
all: $(TARGETS)

# 编译规则
%.out: %.cpp ../../cpp/core/object.cpp
	@echo "编译 $<..."
	$(CXX) $(CXXFLAGS) -o $@ $< ../../cpp/core/object.cpp $(LDFLAGS)
	@echo "✅ 编译完成: $@"

# 运行所有程序
run: $(TARGETS)
	@echo "运行所有程序..."
	@for target in $(TARGETS); do \
		echo ""; \
		echo "=== 运行 $$target ==="; \
		./$$target || echo "❌ $$target 运行失败"; \
		echo ""; \
	done

# 清理
clean:
	@echo "清理编译文件..."
	rm -f *.out *.o
	@echo "✅ 清理完成"

# 显示帮助
help:
	@echo "可用目标:"
	@echo "  all     - 编译所有 C++ 文件"
	@echo "  run     - 运行所有编译后的程序"
	@echo "  clean   - 清理编译文件"
	@echo "  help    - 显示此帮助信息"

.PHONY: all run clean help
EOF

    print_success "已创建 Makefile: $makefile"
}

# 主函数
main() {
    echo "========================================"
    echo "🚀 Dart to C++ 批量转换工具"
    echo "========================================"
    echo
    
    # 检查前置条件
    check_prerequisites
    echo
    
    # 清理输出目录
    clean_output_dir
    echo
    
    # 转换所有文件
    if convert_all_files; then
        echo
        
        # 创建辅助文件
        create_makefile
        
        echo
        print_success "🎉 批量转换完成！"
        print_info "输出目录: $CPP_DIR"
        print_info "使用 'cd $CPP_DIR && make all' 编译所有文件"
        print_info "使用 'cd $CPP_DIR && make run' 运行所有程序"
    else
        echo
        print_error "❌ 批量转换失败，请检查错误信息"
        exit 1
    fi
}

# 脚本入口点
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi